### ISSUE TITLE
Using pseudotime instead of time points

### ISSUE THREAD

**Issue by cnk113** [csjansen/SOMatic#1]
Hello,

Could it be possible to use pseudotime values to build a linked SOM of scATAC and scRNA?
I don't have multiple time points like in your paper, and I was wondering if it was possible to build SOM with scRNA and scATAC from the same tissue from one time point by binning pseudotime?

Thanks

**Comment by csjansen** [comment]
The SOM doesn't use that metadata when training.  It is only used for
labeling the metaclusters into "enriched at this time step" and that is
done at the trait analysis step.  You could bin your psuedotime values into
categories and use those for this labeling if you'd like.  Does that answer
your question?

Also, I have some bug fixes planned for this program and tutorials planned
for submission tomorrow, so you may want to check again then.
