### ISSUE TITLE
GRN inference

### ISSUE THREAD

**Issue by f6v** [csjansen/SOMatic#2]
Thanks for the package!

I was wondering if the package does the inference of GRNs, in general, and in linked clusters?

Kind regards

**Comment by csjansen** [comment]
Hi,

I've been thinking of uploading my GRN inference scripts in a separate depot, but these scripts are for finding linked metaclusters specifically.  GRN inference from that is to just do motif scanning on the linked metaclusters and then a LM enrichment filter. (Not too complicated)
