### ISSUE TITLE
Multi threading with ./buildSiteMT.sh

### ISSUE THREAD

**Issue by amcruise** [csjansen/SOMatic#3]
Hi I would like to specify the number of cores to dedicate to this script, however there is no real specification in the README.md file. It states that the normal and multi-thread versions of the script takes the same options. I see later in the metacluster script that you can specify the number of trials and it will use up to 10 cores? I am confused as to how I might be able to proceed. Thanks for any clarification.

**Comment by csjansen** [comment]
Oh jeez, I didn't see this.

Yes, the metaclustering is multi-threaded on the trials (each trial is it's own program sorta).  When you use more trials, the program will run through metaclustering with random initial conditions and pick the trial with the best overall AIC score.

I hope that helps.

**Comment by amcruise** [comment]
Thanks for your help!
