### ISSUE TITLE
Generating matrix from ChIP data

### ISSUE THREAD

**Issue by harbourlab** [csjansen/SOMatic#4]
Hi! I am having troubles understanding how you would generate the matrix for ChIP data. I have bed files of the peaks called with MACS2, and the partitioning worked. But where do I go from here? Do I really need the SAM files? That would not take into account whether the input for the individual samples is high or low, so I feel SOMatic should be using the MACS2 output directly. Am I missing something? Thanks!

**Comment by csjansen** [comment]
Hi!  Thanks for the interest.

To generate a training matrix for DNA data, you need to use the regionCounts program (in "Generate Training Matrix from RPKMs on the partitions") in the DNA tutorial.  I need to improve the tutorial to make this more clear.

First, you need to convert all of your BAM files to SAM (This could be improved in future versions of the script) using bam/samtools.  Then, put all of the sam file locations (in sample.list order) in a file (1 file location per line).  This will be your "raw sam file list location" file.  

Then you can just run region counts in the scripts folder with your partitions: ./regionCounts.sh -RawDataFile samFiles -Partitions partition.list -Output DNAMatrix -LogScale

Let me know if there are any more issues.

**Comment by harbourlab** [comment]
Thank you for that explanation and quick reply! We love SOMactic!

I will try. Instead of SAM files, which are really clunky, could SOMatic use the MACS2 called peaks for ChIP data instead? These files have been normalized for their respective input, which is a important step in ChIP.

**Comment by csjansen** [comment]
The SOM uses raw signal to perform clustering.  You could also technically make a peak training matrix where each column would be the % of each partition is present in each peak file, but this isn't tested.

You can also use normalized signal from programs like S3Norm.

**Comment by harbourlab** [comment]
Thank You!! Looking forward to testing it out!

Sent from my iPhone

On Dec 29, 2020, at 12:39 PM, csjansen <notifications@github.com> wrote:

﻿
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


The SOM uses raw signal to perform clustering. You could also technically make a peak training matrix where each column would be the % of each partition is present in each peak file, but this isn't tested.

You can also use normalized signal from programs like S3Norm.
