### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by amcruise** [csjansen/SOMatic#5]
Hi , I have previously downloaded and installed SOMatic to my computer and have that running. I am trying to install SOMatic on a remote server. Following the instruction guidelines, after cloning the github repo, I 'cd' into the SOMatic/bin directory and compile with 'make'. The resulting scripts are not executable, for instance: 

./regionCounts.sh: line 28: ../bin/regionCounts/regionCounts: cannot execute binary file. 

I tried dos2unix on the entire scripts directory, and added execute permissions for the scripts. Really do not know how to proceed. I would appreciate any help trouble shooting here! Is it a hardware issue? or remote server environment technicality?

**Comment by csjansen** [comment]
Hi, I have never seen that error before.  I'm not sure, but looks like there might have been an issue compiling that file in that Linux architecture.  Can you share specifics of the server?  It may need specific make options.

**Comment by amcruise** [comment]
Not sure what information may be relevant. I'd appreciate any insight. I have tried mac2unix initially as I scp'ed a compiled SOMatic from my mac onto the server which runs linux. When that did not work I just installed and compiled it on the server directly. Still giving same error. I am also trying to trouble shoot with IT but no response on this front yet! Oddly enough, I can run partition.sh, but it does not seem to like regionCounts.sh.

Here is the CPU architecture:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Stepping:              7
CPU MHz:               1200.000
BogoMIPS:              5199.24
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15

Here is Operating System:

LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.5 (Final)
Release:	6.5

**Comment by csjansen** [comment]
You could try to "make clean" and "make" from inside the regionCounts folder in bin to really force a re-compile.  I'll look into why this could be happening on my end if this works.

**Comment by csjansen** [comment]
Your system might also need an updated g++ compiler.  RegionCounts and metasom both require a c++11 compatible compiler.

**Comment by amcruise** [comment]
That was the issue. Thanks so much! It was not running on a system with GCC 4.4.7. I did not think to switch the compiler because it met the criteria in the documentation. "If this doesn't work, be sure your g++ version is >2.8.2" Could you update it to >= 4.7.3? It ran successfully when compiled with this version.

GCC 4.4.7 Compile Issues : 

..
make[1]: Entering directory `/nethome/kdawsonmed/SOMatic/bin/regionCounts'
g++ main.cpp -O3 -fpermissive -o regionCounts -std=c++11 -pthread
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [build] Error 1
make[1]: Leaving directory `/nethome/kdawsonmed/SOMatic/bin/regionCounts'
make[1]: Entering directory `/nethome/kdawsonmed/SOMatic/bin/score'
..

[kdawsonmed@login1 SOMatic]$ ll bin/partition/
total 52
-rw-r--r-- 1 kdawsonmed ccsuser  3437 Jan 19 15:39 main.cpp
-rw-r--r-- 1 kdawsonmed ccsuser   136 Jan 19 15:39 makefile
-rwxr-xr-x 1 kdawsonmed ccsuser 46294 Jan 19 15:43 partition
[kdawsonmed@login1 SOMatic]$ ll bin/regionCounts/
total 12
-rw-r--r-- 1 kdawsonmed ccsuser 8933 Jan 19 15:39 main.cpp
-rw-r--r-- 1 kdawsonmed ccsuser  162 Jan 19 15:39 makefile

**Comment by csjansen** [comment]
Awesome.  I'll update the documentation.
