### ISSUE TITLE
Core Dump regionCounts.sh

### ISSUE THREAD

**Issue by amcruise** [csjansen/SOMatic#6]
The following script crashes: 

./regionCounts.sh -RawDataFile ../../Harbour/SamFiles/ -Partitions ../../Harbour/partition.list -Output ../../Harbour/ChIP_TrainingMatrix

./regionCounts.sh: line 29: 22634 Segmentation fault      **(core dumped)** ../bin/regionCounts/regionCounts -RawDataFile $RawDataFile -Partitions $Partitions -Output $Outfile

The working directory contains a large core.22634 file. How can I continue the regionCounts program where it left off, using the core.22634 file. The documentation states: 

- "This program makes a number of temporary files in case it crashes to restart where it left off. You can remove them after this program finishes." 

Not sure if the core dump is technically a temporary file the program looks for. Sorry for bugging you with all these bugs. Really trying to get this up and running for an exciting project!

**Comment by amcruise** [comment]
The ./buildSite.sh script works fine with the example training matrix. I am just having difficulty generating a training matrix to build the SOM. I would appreciate any help here!

**Comment by csjansen** [comment]
It looks like you passed regionCounts the folder location of your samfiles and not a file containing the location of the samfiles in the proper order, which is likely why it crashed.  The program, if working, will make a number of .temp files.  You can delete the core dumps.

**Comment by amcruise** [comment]
Whoops that was my complete oversight. It seems to be running properly now although I am unsure if it is parsing through sam files correctly. The following seems to indicate that there are zero mapped reads. 

Reading Partition Data
../Harbour_SOMatic/partition.list
2339329 partitions loaded.
Reading Raw Data
../Harbour_SOMatic/SamFilePaths
Started /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_Ctrl_H3K27AC_trimmed.fq.gz.sam
Started /nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_Ctrl_H3K27AC_trimmed.fq.gz.sam
Started /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_DOX_H3K27AC_trimmed.fq.gz.sam
Started /nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_SH_H3K27AC_trimmed.fq.gz.sam
checking if temp_E1_1_Mel202_Ctrl_H3K27AC_trimmed.fq.gz.sam exists
checking if temp_checking if temp_E2_1_921_DOX_H3K27AC_trimmed.fq.gz.sam exists
E2_1_921_Ctrl_H3K27AC_trimmed.fq.gz.sam exists
checking if temp_E1_1_Mel202_SH_H3K27AC_trimmed.fq.gz.sam exists
/nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_Ctrl_H3K27AC_trimmed.fq.gz.sam
/nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_DOX_H3K27AC_trimmed.fq.gz.sam
Failed?
Opening File
Failed?
Opening File
Building region data structure
Building region data structure/nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_SH_H3K27AC_trimmed.fq.gz.sam

Failed?
Opening File
Building region data structure
/nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_Ctrl_H3K27AC_trimmed.fq.gz.sam
Failed?
Opening File
Building region data structure
Counting: /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_Ctrl_H3K27AC_trimmed.fq.gz.sam 0
Counting: /nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_SH_H3K27AC_trimmed.fq.gz.sam 0
Counting: /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_DOX_H3K27AC_trimmed.fq.gz.sam 0Counting: 
/nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_Ctrl_H3K27AC_trimmed.fq.gz.sam 0
Finished /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_Ctrl_H3K27AC_trimmed.fq.gz.sam
Finished /nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_SH_H3K27AC_trimmed.fq.gz.sam
Finished /nethome/amc606/SOMatic/Harbour/SamFiles/E2_1_921_DOX_H3K27AC_trimmed.fq.gz.sam
Finished /nethome/amc606/SOMatic/Harbour/SamFiles/E1_1_Mel202_Ctrl_H3K27AC_trimmed.fq.gz.sam
0
0
0
0
Outputing Training Matrix

**Comment by csjansen** [comment]
Those sam files have a really odd extension format.  Were these gziped fastqs?  Where did you get these samfiles from?

**Comment by amcruise** [comment]
They were preprocessed, but it ended up working! Currently trying to get the other components of the site built. Thank you so much for your help. Will cite in manuscript once i have it up and running!

**Comment by amcruise** [comment]
This is probably an issue related to the SAM files? 

./getGODNA.sh -SOMName ChIP_SOM -Rows 20 -Cols 30 -Gene2GO ../Harbour_SOMatic/gene2go -GeneInfo ../Harbour_SOMatic/Homo_Sapiens.gene_info -GOFile ../Harbour_SOMatic/go.obo

Getting Go terms
Building GO Heirarchy
Go Heirarchy Number: 0
Getting gene ids
Genes Loaded:61742
Getting Go terms
Computing genes in each GO term
Row: 0 Col: 0	../ChIP_SOM/data/som/genes/gene_0_0.unit
Genes: 0
Row: 0 Col: 1	../ChIP_SOM/data/som/genes/gene_0_1.unit
.... continues .... 

inspection of the training matrix found that no genes were mapped. So it is an upstream error in parsing the SAM files? 

chr1:0-9901     0       0       0       0
chr1:9902-10498 0       0       0       0
chr1:10499-11135        0       0       0       0
chr1:11136-11930        0       0       0       0
chr1:11931-12226        0       0       0       0
chr1:12227-12550        0       0       0       0
chr1:12551-12812        0       0       0       0
... continues ...

**Comment by csjansen** [comment]
Ya, the regionCounts code was definitely spitting out error codes on your samfiles.  Could you double check that they are in those locations and maybe look at the first few lines (using head) to make sure they are in the proper format?  Those fq.gz.sam file are a little weird.

**Comment by amcruise** [comment]
So I have reformatted the Sam files and now region counts is working however it does not produce anything downstream, see following output:

Finished /scratch/projects/hlab/SOMatic-master/Harbour_SOMatic/SamFiles/E2_1_921_DOX_H3K27AC_trimmed.sam
Finished /scratch/projects/hlab/SOMatic-master/Harbour_SOMatic/SamFiles/E1_1_Mel202_Ctrl_H3K27AC_trimmed.sam
Finished /scratch/projects/hlab/SOMatic-master/Harbour_SOMatic/SamFiles/E1_1_Mel202_SH_H3K27AC_trimmed.sam
Finished /scratch/projects/hlab/SOMatic-master/Harbour_SOMatic/SamFiles/E2_1_921_Ctrl_H3K27AC_trimmed.sam
46681895
24083467
29270502
33731571
Outputing Training Matrix
20
30
../bin/trainThread/trainsom -Rows 20 -Cols 30 -TrainingMatrix ../Harbour_SOMatic/ChIP_TrainingMatrix -SOMFile ../ChIP_SOM.som -Trials 5 -Epochs 10 -Topology toroid
Getting Training Matrix Stats
Training Matrix data cols: 4
Timesteps: 826600
Training Matrix lines: 165320
Building data structures
Reading File: ../Harbour_SOMatic/ChIP_TrainingMatrix
line: 10000
line: 20000
line: 30000
line: 40000
line: 50000
line: 60000
line: 70000
line: 80000
line: 90000
line: 100000
line: 110000
line: 120000
line: 130000
line: 140000
line: 150000
line: 160000
Done!
Trial Trial Trial 3 started
0 startedTrial 4 started
1 started
Trial 2 started
Trial 2	 time:10000
Average timestep: (sec) = 3.09751e-05
Trial 1	 time:10000
Average timestep: (sec) = 3.12208e-05
Trial 4	 time:10000
Average timestep: (sec) = 3.17893e-05
Trial 3	 time:10000
Average timestep: (sec) = 4.39654e-05
Trial 0	 time:10000
Average timestep: (sec) = 4.42899e-05
...
...
...
Best Score = 6.35247e+12
Opening SOM file
30
30	1
30
30	2
30
30	3
30
30	4
30
30	5
30
30	6
30
30	7
30
30	8
30
30	9
30
30	10
30
30	11
30
30	12
30
30	13
30
30	14
30
30	15
30
30	16
30
30	17
30
30	18
30
30	19
30
20	30
Opening data file
line: 100000
Done!
Scoring!
Getting winners
Counting up score
Total score: 129104
Inputing SOM file
Inputing Labels
Outputing maps
../ChIP_SOM/data/som/Mel202_Ctrl_H3K27AC.map
../ChIP_SOM/data/som/Mel202_SH_H3K27AC.map
../ChIP_SOM/data/som/921_Ctrl_H3K27AC.map
../ChIP_SOM/data/som/921_DOX_H3K27AC.map
Outputing Summary
Inputing Score file
Creating ../ChIP_SOM/data/som/units/unit_0_0.unit
Creating ../ChIP_SOM/data/som/units/unit_0_1.unit
Creating ../ChIP_SOM/data/som/units/unit_0_2.unit
Creating ../ChIP_SOM/data/som/units/unit_0_3.unit
Creating ../ChIP_SOM/data/som/units/unit_0_4.unit
...
...
...
Getting Go terms
Building GO Heirarchy
Go Heirarchy Number: 0
Getting gene ids
Genes Loaded:61742
Getting Go terms
Computing genes in each GO term
Row: 0 Col: 0	../ChIP_SOM/data/som/genes/gene_0_0.unit
Genes: 0
Row: 0 Col: 1	../ChIP_SOM/data/som/genes/gene_0_1.unit
Genes: 0
Row: 0 Col: 2	../ChIP_SOM/data/som/genes/gene_0_2.unit
Genes: 0
Row: 0 Col: 3	../ChIP_SOM/data/som/genes/gene_0_3.unit
Genes: 0
Row: 0 Col: 4	../ChIP_SOM/data/som/genes/gene_0_4.unit
...
...
...
0	0	0	0
0	1	0	0
0	2	0	0
0	3	0	0
0	4	0	0
0	5	0	0
0	6	0	0
0	7	0	0
0	8	0	0
0	9	0	0
0	10	0	0
0	11	0	0
0	12	0	0
0	13	0	0
0	14	0	0
0	15	0	0
0	16	0	0
0	17	0	0
0	18	0	0
0	19	0	0
0	20	0	0
0	21	0	0
0	22	0	0
0	23	0	0
0	24	0	0
0	25	0	0
0	26	0	0
0	27	0	0
0	28	0	0
0	29	0	0
1	0	0	0
1	1	0	0
1	2	0	0
1	3	0	0
...
...
...

**Comment by csjansen** [comment]
It looks like the GO heirarchy file is either missing or they have messed with the format since I last used this script.  Can you make sure that the go.obo file is a.) downloaded b.) actually a real file c.) passed properly into the getGO script?

**Comment by csjansen** [comment]
Go Heirarchy Number: 0
This line from the GO output makes me think that it wasn't correctly passed in.

**Comment by csjansen** [comment]
I've also been seeing some hard-to-track-down bugs related to the score and unit file generation.  Can you make sure the the unit files have chromatin regions within them?

**Comment by amcruise** [comment]
That could have very well been the error. I followed documentation using:

wget http://purl.obolibrary.org/obo/go.obo

the resulting go.obo file:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://current.geneontology.org/ontology/go.obo">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>

so instead I used the address provided:
http://current.geneontology.org/ontology/go.obo

which output a correct go.obo file. Going to try to re-run now! Also, when displaying the website, there are some bugs in features I think due to file permissions. Is there any way around this? Thanks in advance.

**Comment by csjansen** [comment]
You can chmod 777 -R to recusively give full permissions to all the files in a folder.

**Comment by amcruise** [comment]
so the unit files contain the following:

(base) [amc606@login1 units]$ head unit_0_0.unit 
chr1:10209643-10210505	3.5088
chr1:37157467-37158288	4.8786
chr1:37806941-37809875	6.3308
chr1:46339137-46342292	2.3876
chr1:62687275-62689746	10.693
chr1:75723633-75725364	5.3627
chr1:93344888-93346942	2.346
chr1:147540596-147541274	1.6626
chr1:155243371-155244890	1.3188
chr1:155272414-155274308	5.1841

(base) [amc606@login1 units]$ head unit_9_29.unit 
chr1:12477702-12478498	0.59877
chr1:65247513-65247911	3.1769
chr1:66338128-66339396	0.57865
chr1:107656919-107657516	0.15446
chr1:116679238-116681602	0.73947
chr1:150007807-150008112	1.3074
chr1:185268361-185268823	0.73119
chr1:185938498-185939139	2.1856
chr1:185984445-185985002	0.46198
chr1:226764119-226765148	0.39547

the genes units are empty:
base) [amc606@login1 genes]$ head gene_0_0.unit 
(base) [amc606@login1 genes]$ head gene_9_9.unit
(base) [amc606@login1 genes]$ 

the GO units are empty: 
(base) [amc606@login1 GO]$ head GO_List
(base) [amc606@login1 GO]$ head GO_List_Totals 
(base) [amc606@login1 GO]$ cat GO_0_0.unit 

totals.txt:
(base) [amc606@login1 data]$ head totals.txt 
0	0	0	0
0	1	0	0
0	2	0	0
0	3	0	0
0	4	0	0
0	5	0	0
0	6	0	0
0	7	0	0
0	8	0	0
0	9	0	0

(base) [amc606@login1 data]$ head out.som
# 20 rows	30 cols	4 dimensions	toroid topology
15.17941	18.96279	19.57944	25.00136
11.18993	13.89427	13.23591	17.49668
8.07313	10.61770	9.55421	11.96187
5.41712	7.71983	6.59761	6.25188
3.85134	5.60727	4.42935	2.76086
3.09291	4.25792	3.25665	1.63417
2.62705	3.36349	2.48536	1.21280
2.17171	2.67277	1.70894	0.85928
1.84263	2.18912	1.22104	0.67643

I think the SOM is generated but there are issues with GO and gene mapping. Will make sure gtf file is good.

**Comment by amcruise** [comment]
Update, I changed the GTF file and it is now pulling out genes. Still trying to get GO_terms pulled out. Seems to be a formatting issue with the files being read. 

./getGODNA.sh -SOMName ChIP_SOM -Rows 20 -Cols 30 -Gene2GO ../Harbour_SOMatic/gene2go -GeneInfo ../Harbour_SOMatic/Homo_Sapiens.gene_info -GOFile ../Harbour_SOMatic/go.obo

Getting Go terms
Building GO Heirarchy
Go Heirarchy Number: 44101
Getting gene ids
Genes Loaded:61760
Getting Go terms
Computing genes in each GO term
Row: 0 Col: 0	../ChIP_SOM/data/som/genes/gene_0_0.unit
Genes: 171
Row: 0 Col: 1	../ChIP_SOM/data/som/genes/gene_0_1.unit
Genes: 223
...
...
Row: 19 Col: 28	../ChIP_SOM/data/som/genes/gene_19_28.unit
Genes: 184
Row: 19 Col: 29	../ChIP_SOM/data/som/genes/gene_19_29.unit
Genes: 182
0	0	171	0
0	1	223	0
0	2	208	0
0	3	193	0
0	4	159	0
0	5	151	0
0	6	143	0
0	7	127	0
0	8	117	0
0	9	83	0
0	10	86	0
0	11	65	0
0	12	82	0
0	13	62	0
0	14	113	0
0	15	143	0
0	16		152	0
0	17	104	0

**Comment by csjansen** [comment]
You should make sure that the genes in the gene2go file have the same gene names as the ones in the gene files.

**Comment by amcruise** [comment]
My file are formated the following way:

(base) [amc606@login1 Harbour_SOMatic]$ ls
BedFilePaths  broken_files         full_sample.list                                 gene2go  Homo_Sapiens.gene_info  partition.list  SamFiles
BedFiles      ChIP_TrainingMatrix  gencode.v36.chr_patch_hapl_scaff.annotation.gtf  go.obo   other_bed               SamFilePaths    sample.list


(base) [amc606@login1 Harbour_SOMatic]$ head gene2go
9606	1	GO:0002576	TAS	-	platelet degranulation	-	Process
9606	1	GO:0003674	ND	-	molecular_function	-	Function
9606	1	GO:0005576	HDA	-	extracellular region	27068509	Component
9606	1	GO:0005576	IDA	-	extracellular region	3458201	Component
9606	1	GO:0005576	TAS	-	extracellular region	-	Component
9606	1	GO:0005615	HDA	-	extracellular space	16502470	Component
9606	1	GO:0008150	ND	-	biological_process	-	Process
9606	1	GO:0031093	TAS	-	platelet alpha granule lumen	-	Component
9606	1	GO:0034774	TAS	-	secretory granule lumen	-	Component
9606	1	GO:0043312	TAS	-	neutrophil degranulation	-	Process

(base) [amc606@login1 Harbour_SOMatic]$ head *.gene_info
#tax_id	GeneID	Symbol	LocusTag	Synonyms	dbXrefs	chromosome	map_location	description	type_of_gene	Symbol_from_nomenclature_authority	Full_name_from_nomenclature_authority	Nomenclature_status	Other_designations	Modification_date	Feature_type
9606	1	A1BG	-	A1B|ABG|GAB|HYST2477	MIM:138670|HGNC:HGNC:5|Ensembl:ENSG00000121410	19	19q13.43	alpha-1-B glycoprotein	protein-coding	A1BG	alpha-1-B glycoprotein	O	alpha-1B-glycoprotein|HEL-S-163pA|epididymis secretory sperm binding protein Li 163pA	20201124	-
9606	2	A2M	-	A2MD|CPAMD5|FWP007|S863-7	MIM:103950|HGNC:HGNC:7|Ensembl:ENSG00000175899	12	12p13.31	alpha-2-macroglobulin	protein-coding	A2M	alpha-2-macroglobulin	O	alpha-2-macroglobulin|C3 and PZP-like alpha-2-macroglobulin domain-containing protein 5|alpha-2-M	20201213	-


(base) [amc606@login1 Harbour_SOMatic]$ head *.gtf
##description: evidence-based annotation of the human genome (GRCh38), version 36 (Ensembl 102)
##provider: GENCODE
##contact: gencode-help@ebi.ac.uk
##format: gtf
##date: 2020-09-30
chr1	HAVANA	gene	11869	14409	.	+	.	gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37102"; havana_gene "OTTHUMG00000000961.2";
chr1	HAVANA	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";

Not sure why it wont match the ontology terms to the genes.  Maybe this is a clue: getGenes.sh pulled out ensembl IDs instead of gene names.  

(base) [amc606@login1 genes]$ head gene_1_1.unit 
ENSG00000116717.13
ENSG00000160679.13
ENSG00000271853.5
ENSG00000272030.1
ENSG00000160691.19
ENSG00000173207.13
ENSG00000143761.16
ENSG00000214837.8
ENSG00000107929.15
ENSG00000151461.20

getGODNA.sh will see this and not know what to do with the gene2go, gene_info, and go.obo files?

**Comment by amcruise** [comment]
I mean at this point I can just write a pythonic script to populate the GO unit files, something to this effect, excuse my psuedo code and lack of indents:

with open('GO_X_X.unit','a') as unit:
with open gene2go as g2g: 
for file in genes dir:
file_specific_ensemblID_list =[]
for ensemble.id in file:
list.append(ensembl.id)
for line in g2g:
if line match regex for ensembl.id list:
- regex capture group GO_terms
- unit.write(GO_terms+'\n')

**Comment by csjansen** [comment]
I may need to update the getGene and getGO scripts as it has been a really long time since they have been used.  All of my recent analysis has been from after the metaclustering step as it has been shown that metaclustering provides a more consistant (and thus likely a more "real" clustering).  I will likely move their sections of the README to a seperate file.

**Comment by amcruise** [comment]
Cool no worries! I can also try implementing the metaclustering to get GO terms in there too.

**Comment by amcruise** [comment]
Hey, just following up. So I have not yet got SOMatic's getGO function properly, Idk why it does not like the files. So here is a python script to import GO terms, it does however take around 12 hours to run lol. Need to optimize it, I guess it takes so long because it reads in info for every line. 

#!/usr/bin/env python3

##########################################################################################
### Import Modules

import os
import re
from datetime import datetime
from timer import Timer
from more_itertools import split_before

### Define Directory paths
genes_directory = '/Users/cruz/ChIP_SOM/data/som/genes'
GO_directory = '/Users/cruz/ChIP_SOM/data/som/GO/'

### open data files to parse
gene_info = open('/Users/cruz/SOMatic/Harbour/Homo_Sapiens.gene_info')
g2g = open('/Users/cruz/SOMatic/Harbour/gene2go')
gobo = open('/Users/cruz/SOMatic/Harbour/go.obo')

#### Define global counters to keep track of the process
global_matches = 0
file_counter = 0
general_count = 0
g2g_counter = 0
gobo_counter = 0
gtf_counter = 0
gene_info_counter = 0

### Define global lists/dictionaries to hold parsed data
ID_counts_list = ['',]
human_g2g = []
GI = []
GOBO = []
trim_gobo = []
gobo_dict = {}


t= Timer()
start = datetime.now()


##########################################################################################
#1. Read in Gene Info file store as GI list
for line in gene_info:
	general_count += 1
	if general_count == 1:
		continue
	line = line.rstrip('\n')
	line = line.split('\t')
	GI.append(line)

#2. # parse gobo , get go ID and GO term, build dictionary to match 
for line in gobo:
	gobo_counter += 1
	if 28 < gobo_counter:
		GOBO.append(line)
gobo_list = list(split_before(GOBO,lambda x: x == '[Term]\n'))
for item in gobo_list:
	item.pop(0)
	item= list(map(lambda s: s.strip(), item))
	match_go = item[0]
	match_name = [n for n , l in enumerate(item) if l.startswith('name')]
	match_def = [n for n , l in enumerate(item) if l.startswith('def')]
	try:
		definition = item[match_def[0]]
		name = item[match_name[0]]
	except:
		continue
	matched = re.match('id:\s(GO:.*)',match_go)
	trim_name = re.match('name:\s(.*)',name)
	if matched:
		key = matched.group(1)
		value = trim_name.group(1)
		gobo_dict[key]= value

#3. Parse gene2go and store in a list, using this to match input file Gene IDs to GO terms
##  by using GO ID as a 'primary key'
for line in g2g:
	general_count += 1
	if line.startswith('9606'):
		line = line.rstrip('\n')
		line = line.split('\t')
		g2g_counter += 1
		human_g2g.append(line)

#4. Read in input files which contain ENSG IDs
for filename in os.listdir(genes_directory):
	ID_list = []
	if filename.endswith('.unit'):
		with open(os.path.join(genes_directory,filename)) as ensg:
	# build list and get number of ENSG IDs per file (for counting purposes)
			for ID in ensg:
				ID_list.append(ID)
	global_matches += len(ID_list)
	ID_counts_list.append(len(ID_list))

#5. read in unit file names
for filename in os.listdir(genes_directory):
	file_counter += 1
	if filename.endswith('.unit'):
		t.start()
		# captures the corresponding toroid unit to pass to future GO file
		unit = re.match(r'gene(_.*.unit)', filename)
		print('Mapping GO terms for file {} GO{}'.format(file_counter,unit.group(1)))
		# open gene.unit files to obtain ENSG IDs associated with SOM unit
		with open(os.path.join(genes_directory,filename)) as ensg:
			ID_counter = 0
			ID_list = []
			# open GO file to populate with GO terms down the loop
			GO_units = open(GO_directory+'GO'+unit.group(1),'w')
			# loop through ENSG IDs to query for GO terms
			for ID in ensg:
				# trim down version number to feed to myGene function
				trim = re.match(r'(ENSG.*)\..*', ID)
				if trim:
					ID_counter += 1
					ENSG = trim.group(1)

					current_count = ID_counts_list[file_counter]
					print('Querying {} match #{}/{} out of {}'.format(ENSG,
																	ID_counter,
																	current_count,
																	global_matches))
					# store full ENSG with version number
					IDs = (ID.strip())
					# query GO terms using getgene function from MyGene
####################///////////////////////////////###################################
					
					#query = (mg.getgene(ENSG,'go'))
					# query returns a dictionary of dictionaries so this 
					# is to filter for terms within nested dictionaries
					# this is the major time limiting step in code
					# can improve runtime by importing GO terms from file
					# Need to find primary Keys common in GTF, go.obo, and 
					# gene_info files.

					for item in GI:
						pattern = '.*Ensembl:{}'.format(ENSG)
						hit = re.match(pattern,item[5])
						if hit:
							goIDs = []
							geneID = item[1]
							gene_name = item[2]
		# for entry in human gene 2 go, if g2g gene ID matches Gene Info gene ID, use 
		# g2g GO ID to obtain GO term from gobo_dict
							for go in human_g2g:
								if go[1] == geneID:
									GOID = go[2]
									try:
										GO_units.write(gobo_dict[GOID]+'\n')
									except KeyError:
										continue
									except TypeError:
										continue
			print('Finished unit {} of 600'.format(file_counter))							
			GO_units.close()	
		t.stop()
print('Total run time: ' + str(datetime.now() - start))
