### ISSUE TITLE
Subtract maps to visualize cluster differences between samples

### ISSUE THREAD

**Issue by amcruise** [csjansen/SOMatic#8]
Hi Camden,

I have written a python script to average replicates and obtain the absolute value of the difference between two samples to intuitively visualize cell expression differences between different conditions (ex: mutation status). I was wondering if there is anywhere in SOMatic's code where I can hack the scale to include negative values. Maybe its somewhere in the js or html code? also if you'd like I can contribute some of the python scripts I have made. It may come in handy for other users! 

Thanks in advance for any assistance!

Anthony

**Comment by csjansen** [comment]
If you leave the map file in the proper format in the data/som folder and include the name of the file (minus the .map extension) in the sample.list file in the data folder, you can view any map on the website (even with negative numbers).  You may wish to alter the auto-generated scale from the Groups tab (make a name for the group of SOM's selected, then use a balanced scale e.g (-5,5), so the "white" section is 0.

**Comment by csjansen** [comment]
I also already had a tool included to make the difference maps (dffmap), but I should update the documentation to include it's use as it isn't the most obvious (lots of hacky steps)

**Comment by amcruise** [comment]
Thanks! Yeah thats awesome, I'll give it a try! also any way to alter the color scheme??

**Comment by csjansen** [comment]
You would have to change quite a lot of internal javascript to change the color scheme I'm afraid.  It's fairly hardcoded.

**Comment by clarkzor** [comment]
Hi Camden,

I am a graduate student in Ken Cho's lab at UCI. He has asked me to utilize your SOM software to analyze RNAseq data of treated and untreated conditions. Currently I have been able to install your SOMatic software, and generate .som files using your buildSite.sh script. I may be missing something, but intuitively it seems like I should create treated.som and untreated.som, then utilize your diffmap to create a new .som illustrating the differences between the conditions. I haven't been able to locate diffmap documentation, and it seems like it may be tricky considering your previous thread post. Could you potentially direct me to the diffmap documentation, or give me some advice/help in implementing diffmap? Do I need to utilize diffmap in the ERANGE software from Mortazavi (2013)? If I don't need to use it, and I'm fundamentally misunderstanding something here, please let me know. 

Thank you,
Clark
