### ISSUE TITLE
proteome training matrix

### ISSUE THREAD

**Issue by amcruise** [csjansen/SOMatic#9]
Hi Camden, I am attempting to train a SOM on proteomic data. Here is the structure of the training matrix:

<img width="1066" alt="Screen Shot 2021-03-16 at 4 12 07 PM" src="https://user-images.githubusercontent.com/53617152/111373534-5f685980-8672-11eb-9660-46d6088b67bd.png">

It appears to train succesfully but then it spits out these errors highlighted in **bold**

Average timestep: (sec) = 7.17954e-06
Best Score = 5.74866e+08
Opening SOM file
30
30	1
30
30	2
30
30	3
30
...
...
Opening data file
Done!
Scoring!
Getting winners
Counting up score
Total score: 1047.59
Inputing SOM file
Inputing Labels
Outputing maps
../proteome_SOM/data/som/Pool1.map
../proteome_SOM/data/som/GNAQQ209L.map
../proteome_SOM/data/som/GFP.map
../proteome_SOM/data/som/GNA11_WT.map
../proteome_SOM/data/som/GNA11_VUS.map
../proteome_SOM/data/som/Pool2.map
../proteome_SOM/data/som/KO_GNAQQ209L.map
../proteome_SOM/data/som/KO_GFP.map
../proteome_SOM/data/som/KO_GNA11_WT.map
../proteome_SOM/data/som/KO_GNA11_VUS.map
Outputing Summary
**mv: rename ../proteome_SOM/data/som/summery.map to ../proteome_SOM/data/map_summery.map: No such file or directory**
Inputing Score file
...
...
Creating ../proteome_SOM/data/som/units/unit_19_22.unit
Creating ../proteome_SOM/data/som/units/unit_19_23.unit
Creating ../proteome_SOM/data/som/units/unit_19_24.unit
Creating ../proteome_SOM/data/som/units/unit_19_25.unit
Creating ../proteome_SOM/data/som/units/unit_19_26.unit
Creating ../proteome_SOM/data/som/units/unit_19_27.unit
Creating ../proteome_SOM/data/som/units/unit_19_28.unit
Creating ../proteome_SOM/data/som/units/unit_19_29.unit
**cp: ../proteome_SOM/data/out.som: No such file or directory**

Where could the issue be?? Thanks in advance for any help!

Anthony

**Comment by csjansen** [comment]
Hey Anthony,

These are really strange error messages.  Did you run out of space in the area with SOMatic?  If not, can you check to make sure that a proteome_SOM folder was made in the main SOMatic directory as well as a proteome_SOM.som and proteome_SOM.score file?

-Camden

**Comment by amcruise** [comment]
It looks like there is a correct .som file and a correct .score file but it fails to output the SOM directory!

not sure how to proceed :/ 

<img width="1066" alt="Screen Shot 2021-03-16 at 4 12 07 PM" src="https://user-images.githubusercontent.com/53617152/111642400-71620d80-87d4-11eb-95ef-34eec611c8b4.png">

<img width="757" alt="Screen Shot 2021-03-18 at 10 26 04 AM" src="https://user-images.githubusercontent.com/53617152/111642424-77f08500-87d4-11eb-81ee-9557ca18cd93.png">

<img width="1096" alt="Screen Shot 2021-03-18 at 10 26 25 AM" src="https://user-images.githubusercontent.com/53617152/111642525-8b9beb80-87d4-11eb-979b-77faca208497.png">

**Comment by csjansen** [comment]
I assume you have permission to create directories in the SOMatic folder.  Can you check to be sure that the SOMatic Website.tgz got downloaded correctly?  It should be in that same main directory.

**Comment by amcruise** [comment]
Thanks Camden! that was likely the cause of the error. I had removed the .tgz file on accident. Thanks again Camden, these SOMs are really useful!

**Comment by csjansen** [comment]
Glad to help!

**Comment by amcruise** [comment]
Now it is building the site and SOM properly. For some reason it is not displaying differential SOMs that I created by subtracting different maps. I created the corresponding .map file in the SOM/data/som directory and I added corresponding names to the sample.list file. 

<img width="658" alt="Screen Shot 2021-03-18 at 2 11 31 PM" src="https://user-images.githubusercontent.com/53617152/111675852-f577bd80-87f3-11eb-96e4-fb970cbc6707.png">


<img width="522" alt="Screen Shot 2021-03-18 at 2 13 35 PM" src="https://user-images.githubusercontent.com/53617152/111676170-4b4c6580-87f4-11eb-9764-7efe75bdf4d6.png">

In the website screenshot you can see that I selected one of the differential SOMs that I manually created (The second selected sample). It is not displaying for some reason. I made sure I granted recursive permissions to the entire directory after adding the files. 

Here is a screenshot of successful implementation on an RNA-seq data set. I even used the same script to create the differential map. 

<img width="553" alt="Screen Shot 2021-03-18 at 2 20 36 PM" src="https://user-images.githubusercontent.com/53617152/111677138-4e942100-87f5-11eb-96aa-aad2e98b5d80.png">

**Comment by csjansen** [comment]
Does the WTvKO.map file show up when you browse directly to the file from your browser?

**Comment by amcruise** [comment]
Hmm, it does not!

<img width="727" alt="Screen Shot 2021-03-18 at 2 36 09 PM" src="https://user-images.githubusercontent.com/53617152/111679073-505ee400-87f7-11eb-8b61-0f8e68a5a274.png">

**Comment by csjansen** [comment]
Then apache must not have permission to that file.

**Comment by amcruise** [comment]
<img width="727" alt="Screen Shot 2021-03-18 at 2 36 09 PM" src="https://user-images.githubusercontent.com/53617152/111679600-b8152f00-87f7-11eb-851f-16726c4b7259.png">

<img width="562" alt="Screen Shot 2021-03-18 at 2 39 57 PM" src="https://user-images.githubusercontent.com/53617152/111679718-d418d080-87f7-11eb-810a-731e2ba0b97a.png">


I deleted the previous post because I was double checking that I had looked for the correct directory. I will try to modify apache's httpd.conf file accordingly. I'm not sure why it worked for my previous attempt. I don't think I changed apache's files.

**Comment by amcruise** [comment]
So I inspected the HTML code in the somatic web page to see where the program is not working. It seems like TSSdata.js cannot pull the user created maps even though they are there in the directory. Any insight here?

<img width="1155" alt="Screen Shot 2021-04-03 at 4 12 36 PM" src="https://user-images.githubusercontent.com/53617152/113490496-552ec380-9498-11eb-9649-402a60607150.png">
